language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_19da85edd781_key -iv $encrypted_19da85edd781_iv
  -in ./deploy/travisci_google_service_account.json.enc -out ./deploy/travisci_google_service_account.json
  -d
deploy:
  provider: gae
  keyfile: "./deploy/travisci_google_service_account.json"
  project: dognbone
  skip_cleanup: true
  on:
    branch: master
